# The ck3-tiger.conf file is in standard Paradox script format.
# It should be placed in the top directory of your mod.

filter = {
	show_vanilla = no
	show_loaded_mods = no

	trigger = {
		severity >= Warning
		confidence >= Reasonable

		########################################################################
		# False positives
		########################################################################

		NAND = { # Checks for The Fallen Eagle compatibility, only used with exists
			key = missing-item
			text = "culture soissons not defined in common/culture/cultures/"
		}

		########################################################################
		# False positives due to tiger not updated to 1.20.x
		########################################################################

		NAND = { # New triggers, effects, event targets, and links tiger can't parse
			key = unknown-field
			OR = {
				text = "unknown token `add_tenet`"
				text = "unknown token `change_spiritual_fulfillment`"
				text = "unknown token `every_faith_rite`"
				text = "unknown token `has_personal_tenet_flag`"
				text = "unknown token `has_tenet`"
				text = "unknown token `main_rite`"
				text = "unknown token `remove_tenet`"
				text = "unknown token `rite`"
				text = "unknown token `rite_has_doctrine`"
				text = "unknown token `rite_religion_tag`"
				text = "unknown token `set_character_rite`"
				text = "unknown token `set_character_rite_with_conversion`"
				text = "unknown token `set_county_rite`"
				text = "unknown token `stress_and_fulfillment_impact`"
			}
		}
		NAND = { # New modifiers
			key = unknown-field
			OR = {
				text = "unknown modifier `rite_creation_piety_cost_mult`"
				text = "unknown modifier `rite_modifier`"
			}
		}
		NAND = { # New gui datafunctions
			key = datafunctions
			OR = {
				text = "unknown datafunction GetDoctrineType"
				text = "unknown datafunction GetRiteByKey"
				text = "unknown datafunction GetTenetType"
			}
		}
		NAND = { # New rite: and tenet: prefixes
			key = validation
			OR = {
				text = "unknown prefix `rite`"
				text = "unknown prefix `rite:`"
				text = "unknown prefix `tenet`"
			}
		}
		NAND = { # Laws are now top-level objects, with law groups moved to common/law_groups/
			key = missing-item
			text = " not defined in common/laws/"
		}
		NAND = { # Faiths moved to common/religion/faith_types/
			key = missing-item
			OR = {
				text = " not defined in common/religion/religions/"
				text = "could not find any manichaean_faith"
				text = "could not find any miaphysitism"
			}
		}
		NAND = { # Doctrine and tenet parameters are now lists in common/religion/doctrine_types/ and common/religion/tenet_types/
			key = missing-item
			text = " not defined in common/religion/doctrine_types/"
		}
		NAND = { # Doctrine parameters are now lists of flags
			key = structure
			text = "found loose value"
			file = common/religion/doctrine_types/
		}
		NAND = { # family moved into religion_details in religion types
			key = field-missing
			text = "required field `family` missing"
			file = common/religion/religion_types/
		}
	}
}
